name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Get PR Diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt

      - name: Run AI Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 -c "
import openai
openai.api_key = '${{ secrets.OPENAI_API_KEY }}'
with open('diff.txt') as f:
    diff = f.read()
prompt = f\"\"\"
You are a senior software engineer. Review the following code changes and provide:
- Summary
- Suggestions for improvement
- Key risks
- Test case considerations

Code Diff:
{diff}
\"\"\"
response = openai.ChatCompletion.create(
    model='gpt-4',
    messages=[
        {'role': 'system', 'content': 'You are a code reviewer AI.'},
        {'role': 'user', 'content': prompt}
    ]
)
print(response['choices'][0]['message']['content'])
"
