name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ✅ Use a supported version

      - name: Install dependencies
        run: pip install requests

      - name: Get diff between base and head commits
        run: |
          echo "Getting diff between ${{ github.event.pull_request.base.sha }} and ${{ github.event.pull_request.head.sha }}"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }}...HEAD > diff.txt

      - name: Run AI Review with AIMLAPI
        run: python .github/scripts/review_aimlapi.py
        env:
          AIML_API_KEY: ${{ secrets.AIML_API_KEY }}
