name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get diff between commits
        run: |
          echo "Getting diff between commits..."
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}...HEAD > diff.txt

      - name: Run AI code review
        env:
          AIMLAPI_KEY: ${{ secrets.AIMLAPI_KEY }}
        run: |
          python .github/scripts/review_aimlapi.py
