name: AI Code Review

on:
  pull_request:
    branches:
      - main
      - 'feature/**'   # or any branches you want to monitor

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # fetch history for diff

      - name: Get diff from PR
        id: diff
        run: |
          # Get diff between base and head commits
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }} > diff.txt
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          cat diff.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run AI Code Review
        env:
          AIMLAPI_API_KEY: ${{ secrets.AIMLAPI_API_KEY }}
        run: |
          python .github/scripts/review_aimlapi.py
